version: '3'

networks:
  observability-example:
    driver: bridge

services:
  listd:
    build:
      context: .
      dockerfile: ./cmd/listd/deploy/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db
    restart: on-failure
    networks:
      - observability-example
  db:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: list
    restart: on-failure
    networks:
      - observability-example
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./deploy/prometheus.yml:/etc/prometheus/prometheus.yml"
    restart: on-failure
    networks:
      - observability-example
  loki: # add config file
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    restart: on-failure
    depends_on:
      - promtail
    networks:
      - observability-example
  promtail: # add config file
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    restart: on-failure
    depends_on:
      - listd
    networks:
      - observability-example
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - prometheus
      - loki
    networks:
      - observability-example